modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "mcef_adblock"
version = "${version}"
displayName = "MCEF AdBlock"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.mcef_adblock]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcef_adblock]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "mcef-adblock.mixins.json"
